foreground         #c2c2c5
background         #0b0e19
background_opacity 1.0
cursor             #c2c2c5

active_tab_foreground     #0b0e19
active_tab_background     #c2c2c5
inactive_tab_foreground   #c2c2c5
inactive_tab_background   #0b0e19

active_border_color   #c2c2c5
inactive_border_color #0b0e19
bell_border_color     #5a6996

color0       #0b0e19
color8       #5a5e6e
color1       #5a6996
color9       #788CC8
color2       #636b8b
color10      #848FBA
color3       #717e9e
color11      #97A9D3
color4       #7280a2
color12      #99ABD9
color5       #918cb4
color13      #C2BBF1
color6       #8998aa
color14      #B7CBE3
color7       #8e9099
color15      #c2c2c5
